name: Criar Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Criar ZIP
        run: |
          mkdir "projeto-${GITHUB_REF_NAME}"

          git archive \
            --format=zip \
            --output="projeto-${GITHUB_REF_NAME}.zip" \
            HEAD

      - name: Criar Release
        run: |
          gh release create "${GITHUB_REF_NAME}" \
            "projeto-${GITHUB_REF_NAME}.zip" \
            --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
